
dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
install:
  - dotnet restore CloseEnoughEquality.sln
script:
- dotnet test -f netcoreapp1.0 tests/CloseEnoughEquality.Tests/CloseEnoughEquality.Tests.csproj
