environment:
  build_version: 2.0.1
  Version: $(build_version)
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
- cmd: nuget restore CloseEnoughEquality.sln
build:
  project: CloseEnoughEquality.sln
  publish_nuget: true
  verbosity: minimal
test:
  assemblies:
    - '**\*.tests.dll'
os: Visual Studio 2022
